SELECT count(*)
FROM EMP e 

SELECT count(*)
FROM EMP e 
WHERE DEPTNO = 20 OR MGR <= 7700


SELECT MIN(SAL)
FROM EMP e 
WHERE DEPTNO = 10 OR DEPTNO = 20

SELECT DEPTNO, avg(SAL)
FROM EMP 
GROUP BY DEPTNO

SELECT DEPTNO, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO
ORDER BY DEPTNO 

SELECT DEPTNO, avg(SAL)
FROM EMP 
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO DESC 

SELECT COUNT(*), AVG(SAL) 
FROM EMP 
WHERE JOB = 'MANAGER'

SELECT COUNT(*) 
FROM EMP 
WHERE ENAME LIKE '%S%'

SELECT COUNT(*) 
FROM EMP 
WHERE SAL >= 3000 AND COMM IS NOT NULL 
ORDER BY SAL DESC